default:
  content:
    - name: "Penguins Dashboard"
      path: "./shiny-penguins"
      description: "A dashboard of penguin data measurements, built with Shiny for R."
      tag:
        - "Examples|R|Shiny"
      url: "/r-examples/shiny-penguins/"
      image: "./shiny-penguins/imgs/app-screenshot.png"
    - name: "Penguins API"
      path: "./plumber-penguins/app"
      description: "An API serving penguin data measurements, built with Plumber."
      tag:
        - "Examples|R|Plumber"
      url: "/r-examples/plumber-penguins/"
      image: "./plumber-penguins/imgs/screenshot.png"
    - name: "Penguins Document"
      path: "./rmd-penguins/report"
      description: "A report of penguin data measurements, built with R Markdown."
      tag:
        - "Examples|R|R Markdown"
      url: "/r-examples/rmd-penguins/"
      image: "./rmd-penguins/report/imgs/culmen_depth.png"