default:
  content:
    - name: "Penguins API"
      path: "./app"
      description: "An API serving penguin data measurements, built with Plumber."
      tag:
        - "Examples|R|Plumber"
      url: "/r-examples/plumber-penguins/"
      image: "./imgs/screenshot.png"
