name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: deploy
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ secrets.CONNECT_API_KEY }}@colorado.posit.co/rsc
          namespace: r-examples
          dir: |
            ./connectwidgets-penguins/app
            ./pins-r-penguins/report
            ./plumber-penguins/app
            ./plumber-tableau-penguins/app
            ./rmd-blastula
            ./rmd-flexdashboard-parameterized-sales
            ./rmd-penguins/report
            ./shiny-penguins
          require-vanity-path: true
          access-type: all
